name: BuildersEssentials
main: main.BuildersEssentials
authors:
website: "https://github.com/SimonAtelier"
version: 0.0.0
depend: []
softdepend: []
commands:
  bes:
    description:
    usage: /<command>
    permission: